version: "3.7"

services:
  terraform:
    build:
      context: .
      target: terraform
      args:
        TF_VERSION: ${TF_VERSION-1.0.0}
    container_name: terraform-${TF_ENV-nindevdo}-${TF_VERSION-1.0.0}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - TF_VAR_tf_version=${TF_VERSION-1.0.0}
    entrypoint: /bin/bash
    volumes:
      - ${PWD}:/${TF_ENV-nindevdo}
    tty: true
    working_dir: /${TF_ENV-nindevdo}